import {NextResponse} from "next/server";
import {supabaseAdmin} from "@/lib/supabase-admin";
import {loadPlanningIntelligence} from "@/lib/planning-intelligence";
const n=(v:any)=>Number(v||0); const d=(v:any)=>String(v||"").slice(0,10);
const days=(a:string,b:string)=>Math.round((new Date(`${b}T00:00:00`).getTime()-new Date(`${a}T00:00:00`).getTime())/86400000);
export async function GET(req:Request){try{const u=new URL(req.url),date=u.searchParams.get("date")||new Date().toISOString().slice(0,10);const intel=await loadPlanningIntelligence(date);
 const [opsR,poR,repR,dhR,diR]=await Promise.all([
  supabaseAdmin.from("production_operations").select("id,wo_code,operation_name"),
  supabaseAdmin.from("production_orders").select("id,root_id,order_id,operation_id,status,quantity,level_no").eq("level_no",3),
  supabaseAdmin.from("production_reports").select("report_date,production_order_id,good_qty,ng_qty").lte("report_date",date),
  supabaseAdmin.from("production_dispatch_headers").select("id,dispatch_date,operation_id,status,capacity_value,planned_quantity").eq("dispatch_date",date),
  supabaseAdmin.from("production_dispatch_items").select("id,dispatch_id,production_order_id,quantity")]);
 for(const r of[opsR,poR,repR,dhR,diR])if(r.error)throw r.error;
 const opMap=new Map((opsR.data||[]).map(x=>[x.id,x])); const poMap=new Map((poR.data||[]).map(x=>[x.id,x]));
 const good=new Map<string,number>(),ng=new Map<string,number>();for(const r of repR.data||[]){good.set(r.production_order_id,(good.get(r.production_order_id)||0)+n(r.good_qty));ng.set(r.production_order_id,(ng.get(r.production_order_id)||0)+n(r.ng_qty))}
 const action:any[]=[]; const risks=intel.roots.filter(x=>x.rootStatus!=="COMPLETED").map(x=>{const dd=days(date,x.dueDate);let score=0;const reasons:string[]=[];if(dd<0){score+=60;reasons.push(`Trễ ${Math.abs(dd)} ngày`)}else if(dd<=2){score+=35;reasons.push(dd===0?"Giao hôm nay":`Còn ${dd} ngày`)}else if(dd<=5){score+=15;reasons.push(`Còn ${dd} ngày`)}if(["SHORTAGE","HOLD"].includes(x.materialStatus)){score+=30;reasons.push(`Vật tư ${x.materialStatus}`)}if(x.qualityHold){score+=35;reasons.push("Quality Hold")}if(x.setGap>0){score+=Math.min(25,5+Math.round(x.setGap/2));reasons.push(`Set Gap ${x.setGap}`)}const risk=score>=70?"LATE/BLOCKED":score>=40?"AT RISK":"ON TRACK";return{...x,daysToDue:dd,riskScore:score,risk,reasons:reasons.join(" • ")}}).sort((a,b)=>b.riskScore-a.riskScore);
 for(const x of risks){if(x.risk!=="ON TRACK")action.push({severity:x.risk==="LATE/BLOCKED"?"HIGH":"MEDIUM",type:"DELIVERY",title:x.orderNo,detail:x.reasons,href:"/delivery-risk"});if(["SHORTAGE","HOLD"].includes(x.materialStatus))action.push({severity:"HIGH",type:"MATERIAL",title:x.orderNo,detail:`${x.materialStatus} • ${x.materialNote||"Cần xử lý vật tư"}`,href:"/material-readiness"});if(x.qualityHold)action.push({severity:"HIGH",type:"QUALITY",title:x.orderNo,detail:"Quality Hold đang chặn kế hoạch",href:"/quality"})}
 for(const x of intel.operationLoad.filter(x=>x.loadPercent>100))action.push({severity:"HIGH",type:"CAPACITY",title:x.woCode,detail:`Tải ${x.loadPercent}% • vượt ${Math.max(0,x.planned-x.capacity)} bộ`,href:"/schedule-board"});
 for(const x of intel.lots.filter(x=>x.setGap>0).slice(0,8))action.push({severity:"MEDIUM",type:"SET GAP",title:x.lotNo,detail:`${x.bottleneckBranch} bottleneck • Gap ${x.setGap} bộ`,href:"/bottleneck"});
 const common=(poR.data||[]).filter(p=>Number(String(opMap.get(p.operation_id)?.wo_code||'').replace(/\D/g,''))>=14);const commonByRoot=new Map<string,any[]>();for(const p of common){const a=commonByRoot.get(p.root_id)||[];a.push(p);commonByRoot.set(p.root_id,a)}
 const shipping=intel.roots.map(x=>{const rows=commonByRoot.get(x.rootId)||[];const all=rows.length>0&&rows.every(p=>p.status==="COMPLETED");const some=rows.some(p=>p.status==="COMPLETED");let status="IN PRODUCTION";if(x.qualityHold)status="BLOCKED";else if(all)status="READY TO SHIP";else if(x.setReady>=x.quantity&&rows.length===0)status="READY TO PACK";else if(x.setReady>0||some)status="PARTIAL READY";return{...x,shippingStatus:status,commonCompleted:rows.filter(p=>p.status==="COMPLETED").length,commonTotal:rows.length}});
 const todayHeaders=dhR.data||[],todayIds=new Set(todayHeaders.map(x=>x.id)),todayItems=(diR.data||[]).filter(x=>todayIds.has(x.dispatch_id));let carry=0;for(const i of todayItems){const g=good.get(i.production_order_id)||0;carry+=Math.max(0,n(i.quantity)-g)}
 const lossByWo=new Map<string,{wo:string,name:string,good:number,ng:number,planned:number,capacity:number}>();for(const h of todayHeaders){const op=opMap.get(h.operation_id);if(!op)continue;lossByWo.set(op.wo_code,{wo:op.wo_code,name:op.operation_name,good:0,ng:0,planned:n(h.planned_quantity),capacity:n(h.capacity_value)})}for(const i of todayItems){const p=poMap.get(i.production_order_id),op=p?opMap.get(p.operation_id):null,row=op?lossByWo.get(op.wo_code):null;if(row){row.good+=good.get(i.production_order_id)||0;row.ng+=ng.get(i.production_order_id)||0}}
 const losses=[...lossByWo.values()].map(x=>({...x,lostCapacity:Math.max(0,x.capacity-x.good),reworkHours:+(x.ng*0.35).toFixed(1),overtimeHours:+(Math.max(0,x.planned-x.capacity)*0.12).toFixed(1)}));
 const meeting={planned:todayHeaders.reduce((s,x)=>s+n(x.planned_quantity),0),capacity:todayHeaders.reduce((s,x)=>s+n(x.capacity_value),0),carryOver:carry,topRisks:risks.slice(0,5),topBottlenecks:intel.lots.filter(x=>x.setGap>0).sort((a,b)=>b.setGap-a.setGap).slice(0,5),materialIssues:intel.kpi.materialShortage,qualityIssues:intel.kpi.openQuality,setReady:intel.kpi.setReadyQty,overloads:intel.kpi.overloadedWorkCenters};
 return NextResponse.json({success:true,date,risks,actions:action.slice(0,100),shipping,meeting,losses,kpi:intel.kpi,recommendations:intel.smartRecommendations});
 }catch(e){return NextResponse.json({success:false,message:e instanceof Error?e.message:"Không tải được dữ liệu"},{status:500})}}
