"use client";
import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/app-shell";

type Mat = {materialId:string;code:string;name:string;category:string;uom:string;onHand:number;reserved:number;safetyStock:number;netAvailable:number;demand:number;shortage:number;coveragePercent:number;impactedOrders:number;status:string};
export default function Page(){
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(""),[working,setWorking]=useState(false),[filter,setFilter]=useState("ALL");
 async function load(){const r=await fetch("/api/planning/material-requirements",{cache:"no-store"});const j=await r.json();if(j.success)setData(j);else setMessage(j.message)}
 useEffect(()=>{load()},[]);
 async function action(body:any){setWorking(true);setMessage("");try{const r=await fetch("/api/planning/material-requirements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.success)throw new Error(j.message);setData(j);setMessage(j.message)}catch(e){setMessage(e instanceof Error?e.message:"Không thể xử lý") }finally{setWorking(false)}}
 const rows:Mat[]=useMemo(()=>((data?.materials||[]) as Mat[]).filter(x=>filter==="ALL"||x.status===filter),[data,filter]);
 return <AppShell><main className="mx-auto max-w-[1800px] p-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-emerald-600">MRP LIGHT • MATERIAL REQUIREMENT</p><h1 className="mt-1 text-2xl font-black">Nhu cầu & thiếu hụt vật tư</h1><p className="mt-1 text-sm text-slate-500">BOM demand → On-hand → Reserved → Safety stock → Shortage → Material Readiness.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-lg border px-4 py-2 text-sm font-bold">Tải lại</button><button disabled={working} onClick={()=>action({action:"recalculate"})} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Tính lại Readiness</button></div></div>
  {message&&<div className="mt-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{message}</div>}
  <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><K t="Material Master" v={data?.kpi?.materialCount??0}/><K t="Material Shortage" v={data?.kpi?.shortageMaterials??0} danger/><K t="Tổng thiếu hụt" v={data?.kpi?.shortageQty??0} danger/><K t="Đơn bị ảnh hưởng" v={data?.kpi?.impactedOrders??0} danger/><K t="Tổng nhu cầu" v={data?.kpi?.totalDemand??0}/></div>
  <div className="mt-4 flex flex-wrap gap-2">{["ALL","SHORTAGE","LOW","OK"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${filter===x?"bg-slate-900 text-white":"bg-white"}`}>{x}</button>)}</div>
  <section className="mt-4 overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="min-w-[1200px] w-full text-xs"><thead className="bg-slate-900 text-white"><tr><Th>Mã</Th><Th>Vật tư</Th><Th>Nhóm</Th><Th>On-hand</Th><Th>Reserved</Th><Th>Safety</Th><Th>Net available</Th><Th>Demand</Th><Th>Shortage</Th><Th>Coverage</Th><Th>Đơn ảnh hưởng</Th><Th>Điều chỉnh tồn</Th></tr></thead><tbody>{rows.map(x=><MaterialRow key={x.materialId} row={x} working={working} onSave={(onHand,reserved)=>action({action:"update_inventory",materialId:x.materialId,onHand,reserved})}/>)}</tbody></table></div></section>
  <section className="mt-5 rounded-xl border bg-white p-4"><h2 className="font-black">Đơn hàng / LSX và BOM Requirement</h2><div className="mt-3 max-h-[460px] overflow-auto"><table className="min-w-[1200px] w-full text-xs"><thead className="sticky top-0 bg-slate-100"><tr><Th>LSX</Th><Th>Đơn</Th><Th>Ngày giao</Th><Th>Model</Th><Th>SL</Th><Th>Material Requirement</Th></tr></thead><tbody>{(data?.orders||[]).slice(0,100).map((x:any)=><tr key={x.rootId} className="border-t"><Td><b>{x.productionNo}</b></Td><Td>{x.orderNo}</Td><Td>{x.dueDate}</Td><Td>{x.model}</Td><Td>{x.quantity}</Td><Td>{x.requirements.map((r:any)=>`${r.code}: ${r.requiredQty} ${r.uom}`).join(" • ")||"Chưa có BOM"}</Td></tr>)}</tbody></table></div></section>
 </main></AppShell>
}
function MaterialRow({row,working,onSave}:{row:Mat;working:boolean;onSave:(a:number,b:number)=>void}){const[a,setA]=useState(row.onHand),[b,setB]=useState(row.reserved);useEffect(()=>{setA(row.onHand);setB(row.reserved)},[row.onHand,row.reserved]);return <tr className={`border-t ${row.status==="SHORTAGE"?"bg-red-50":row.status==="LOW"?"bg-amber-50":""}`}><Td><b>{row.code}</b></Td><Td>{row.name}</Td><Td>{row.category}</Td><Td>{row.onHand} {row.uom}</Td><Td>{row.reserved}</Td><Td>{row.safetyStock}</Td><Td><b>{row.netAvailable}</b></Td><Td>{row.demand}</Td><Td><b className={row.shortage>0?"text-red-600":"text-emerald-600"}>{row.shortage}</b></Td><Td>{row.coveragePercent}%</Td><Td>{row.impactedOrders}</Td><Td><div className="flex gap-1"><input type="number" value={a} onChange={e=>setA(Number(e.target.value))} className="w-20 rounded border px-2 py-1"/><input type="number" value={b} onChange={e=>setB(Number(e.target.value))} className="w-20 rounded border px-2 py-1"/><button disabled={working} onClick={()=>onSave(a,b)} className="rounded bg-blue-600 px-2 py-1 font-bold text-white">Lưu</button></div></Td></tr>}
function K({t,v,danger=false}:{t:string;v:any;danger?:boolean}){return <div className={`rounded-xl border p-4 ${danger?"border-red-200 bg-red-50":"bg-white"}`}><div className="text-[10px] font-black uppercase text-slate-500">{t}</div><div className={`mt-1 text-2xl font-black ${danger?"text-red-700":""}`}>{v}</div></div>}
function Th({children}:{children:any}){return <th className="px-3 py-3 text-left font-bold">{children}</th>}function Td({children}:{children:any}){return <td className="px-3 py-3 align-top">{children}</td>}
