import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { loadPlanningIntelligence } from "@/lib/planning-intelligence";
import { loadMaterialRequirements } from "@/lib/material-requirements";

function daysBetween(a:string,b:string){if(!a||!b)return 999;return Math.round((new Date(`${a}T00:00:00`).getTime()-new Date(`${b}T00:00:00`).getTime())/86400000)}
export async function GET(request:Request){try{
 const url=new URL(request.url);const date=url.searchParams.get("date")||new Date().toISOString().slice(0,10);
 const [intel,material,headersR,itemsR,reportsR,wipR]=await Promise.all([
  loadPlanningIntelligence(date),loadMaterialRequirements(date),
  supabaseAdmin.from("production_dispatch_headers").select("id,operation_id,dispatch_date,status,planned_quantity").eq("status","RELEASED").lte("dispatch_date",date),
  supabaseAdmin.from("production_dispatch_items").select("id,dispatch_id,production_order_id,quantity"),
  supabaseAdmin.from("production_reports").select("dispatch_item_id,good_qty,report_date").lte("report_date",date),
  supabaseAdmin.from("production_wip_settings").select("operation_id,wip_min,wip_target,wip_max,is_active").eq("is_active",true)
 ]);for(const r of[headersR,itemsR,reportsR,wipR])if(r.error)throw r.error;
 const headers=headersR.data??[],items=itemsR.data??[],reports=reportsR.data??[];
 const hMap=new Map(headers.map(x=>[x.id,x]));
 const hIds=new Set(headers.map(x=>x.id));
 const histHeaderIds=new Set(headers.filter(x=>String(x.dispatch_date)<date).map(x=>x.id));
 const histItems=items.filter(x=>histHeaderIds.has(x.dispatch_id));const goodMap=new Map<string,number>();for(const r of reports)goodMap.set(r.dispatch_item_id,(goodMap.get(r.dispatch_item_id)??0)+Number(r.good_qty||0));const carryOver=histItems.reduce((s,x)=>s+Math.max(0,Number(x.quantity||0)-(goodMap.get(x.id)??0)),0);
 const wipByOp=new Map<string,number>();for(const item of items.filter(x=>hIds.has(x.dispatch_id))){const h=hMap.get(item.dispatch_id);if(!h)continue;const remain=Math.max(0,Number(item.quantity||0)-(goodMap.get(item.id)??0));wipByOp.set(h.operation_id,(wipByOp.get(h.operation_id)??0)+remain)}
 const wipSettings=new Map((wipR.data??[]).map(x=>[x.operation_id,x]));
 const wipPressure=[...wipByOp.entries()].map(([operationId,current])=>{const st=wipSettings.get(operationId);const status=!st?"NO_SETTING":current<Number(st.wip_min||0)?"LOW":current>Number(st.wip_max||0)?"HIGH":"OK";return{operationId,current,min:Number(st?.wip_min||0),target:Number(st?.wip_target||0),max:Number(st?.wip_max||0),status}});
 const materialShortRoots=new Set(material.orders.filter((row:any)=>row.materialStatus!=="READY").map((x:any)=>x.rootId));
 const risks=intel.roots.map(root=>{const days=daysBetween(root.dueDate,date);let level="ON_TRACK",score=0;const reasons:string[]=[];if(days<0&&root.rootStatus!=="COMPLETED"){level="LATE";score+=100;reasons.push(`Trễ ${Math.abs(days)} ngày`)}else if(days<=2&&root.rootStatus!=="COMPLETED"){level="AT_RISK";score+=60;reasons.push("Sắp đến hạn giao")}if(materialShortRoots.has(root.rootId)){level=level==="LATE"?level:"AT_RISK";score+=35;reasons.push("Thiếu vật tư")}if(root.qualityHold){level="BLOCKED";score+=50;reasons.push("Quality Hold")}if(root.setGap>0&&days<=5){score+=25;reasons.push(`Set Gap ${root.setGap}`);if(level==="ON_TRACK")level="AT_RISK"}return {...root,riskLevel:level,riskScore:score,riskReasons:reasons.join(" • ")||"Đúng tiến độ"}}).sort((a,b)=>b.riskScore-a.riskScore);
 const actions:any[]=[];for(const r of risks.filter(x=>x.riskLevel!=="ON_TRACK").slice(0,8))actions.push({severity:r.riskLevel==="LATE"||r.riskLevel==="BLOCKED"?"HIGH":"MEDIUM",type:"DELIVERY",title:r.orderNo,detail:r.riskReasons,href:"/delivery-risk"});for(const m of material.materials.filter((x:any)=>x.shortage>0).slice(0,5))actions.push({severity:"HIGH",type:"MATERIAL",title:m.code,detail:`Thiếu ${m.shortage} ${m.uom} • ảnh hưởng ${m.impactedOrders} đơn`,href:"/material-requirements"});for(const l of intel.lots.filter(x=>x.setGap>0).sort((a,b)=>b.setGap-a.setGap).slice(0,5))actions.push({severity:"MEDIUM",type:"BOTTLENECK",title:l.lotNo,detail:`${l.bottleneckBranch} • Set Gap ${l.setGap} bộ`,href:"/bottleneck"});for(const o of intel.operationLoad.filter(x=>x.loadPercent>100).slice(0,5))actions.push({severity:"HIGH",type:"CAPACITY",title:o.woCode,detail:`Load ${o.loadPercent}% • ${o.operationName}`,href:"/schedule-board"});for(const w of wipPressure.filter(x=>x.status!=="OK"&&x.status!=="NO_SETTING").slice(0,5)){const op=intel.operationLoad.find(x=>x.operationId===w.operationId);actions.push({severity:w.status==="HIGH"?"HIGH":"MEDIUM",type:"WIP",title:op?.woCode||"WO",detail:`WIP ${w.current} • Min/Target/Max ${w.min}/${w.target}/${w.max}`,href:"/configuration"})}
 return NextResponse.json({success:true,date,kpi:{late:risks.filter(x=>x.riskLevel==="LATE").length,atRisk:risks.filter(x=>x.riskLevel==="AT_RISK").length,blocked:risks.filter(x=>x.riskLevel==="BLOCKED").length,materialShortage:material.kpi.shortageMaterials,materialShortageQty:material.kpi.shortageQty,setReady:intel.kpi.setReadyQty,setGap:intel.kpi.setGapQty,bottleneckLots:intel.lots.filter(x=>x.setGap>0).length,qualityHold:intel.kpi.qualityHold,overload:intel.kpi.overloadedWorkCenters,carryOver,wipLow:wipPressure.filter(x=>x.status==="LOW").length,wipHigh:wipPressure.filter(x=>x.status==="HIGH").length,recommendations:intel.kpi.recommendationCount},risks:risks.slice(0,15),actions:actions.sort((a,b)=>(a.severity==="HIGH"?-1:1)-(b.severity==="HIGH"?-1:1)).slice(0,16),loads:intel.operationLoad.sort((a,b)=>b.loadPercent-a.loadPercent).slice(0,12),lots:intel.lots.sort((a,b)=>b.setGap-a.setGap).slice(0,10),material:material.materials.slice(0,10)});
}catch(error){return NextResponse.json({success:false,message:error instanceof Error?error.message:"Không tải được Control Tower."},{status:500})}}
