"use client";
import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/app-shell";
const today=()=>new Date().toISOString().slice(0,10);
export default function Page(){const[date,setDate]=useState(today()),[data,setData]=useState<any>(null),[filter,setFilter]=useState("ALL"),[search,setSearch]=useState("");useEffect(()=>{fetch(`/api/planning/set-matching?date=${date}`,{cache:"no-store"}).then(r=>r.json()).then(j=>j.success&&setData(j))},[date]);const rows=useMemo(()=>((data?.rows||[]) as any[]).filter(x=>(filter==="ALL"||x.matchStatus===filter)&&(!search||`${x.orderNo} ${x.productionNo} ${x.matchKey}`.toLowerCase().includes(search.toLowerCase()))),[data,filter,search]);return <AppShell><main className="mx-auto max-w-[1800px] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-indigo-600">SET MATCHING ENGINE</p><h1 className="mt-1 text-2xl font-black">Matching Cánh • Khung • Phào theo cấu hình</h1><p className="mt-1 text-sm text-slate-500">Order + Model + Size + Color + Opening + Hardware → chỉ ghép đúng cấu hình của cùng LSX.</p></div><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-10 rounded-lg border px-3"/></div>
<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-7"><K t="Full Match" v={data?.kpi?.full??0} tone="green"/><K t="Partial" v={data?.kpi?.partial??0} tone="amber"/><K t="Not Ready" v={data?.kpi?.notReady??0}/><K t="Quality Hold" v={data?.kpi?.hold??0} tone="red"/><K t="Missing Attr" v={data?.kpi?.missing??0} tone="red"/><K t="Matched Qty" v={data?.kpi?.matchedQty??0} tone="green"/><K t="Unmatched Qty" v={data?.kpi?.unmatchedQty??0} tone="amber"/></div>
<div className="mt-4 flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm đơn / LSX / Match Key..." className="h-10 min-w-[280px] flex-1 rounded-lg border px-3 text-sm"/>{["ALL","FULL_MATCH","PARTIAL_MATCH","NOT_READY","HOLD","MISSING_ATTR"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${filter===x?"bg-slate-900 text-white":"bg-white"}`}>{x}</button>)}</div>
<section className="mt-4 overflow-hidden rounded-xl border bg-white"><div className="overflow-x-auto"><table className="min-w-[1500px] w-full text-xs"><thead className="bg-slate-900 text-white"><tr><Th>Đơn / LSX</Th><Th>Match Key</Th><Th>SL</Th><Th>Cánh Ready</Th><Th>Khung Ready</Th><Th>Phào Ready</Th><Th>Matched</Th><Th>Unmatched</Th><Th>Status</Th><Th>Mismatch / Block</Th></tr></thead><tbody>{rows.map(x=><tr key={x.rootId} className={`border-t ${x.matchStatus==="HOLD"||x.matchStatus==="MISSING_ATTR"?"bg-red-50":x.matchStatus==="PARTIAL_MATCH"?"bg-amber-50":""}`}><Td><b>{x.orderNo}</b><div className="text-slate-500">{x.productionNo}</div></Td><Td><div className="max-w-[420px] font-mono text-[10px]">{x.matchKey}</div></Td><Td>{x.quantity}</Td><Td>{x.canhReady}</Td><Td>{x.khungReady}</Td><Td>{x.phaoReady}</Td><Td><b className="text-emerald-700">{x.matchedQty}</b></Td><Td><b className="text-amber-700">{x.unmatchedQty}</b></Td><Td><Pill v={x.matchStatus}/></Td><Td>{x.mismatchReason}</Td></tr>)}</tbody></table></div></section>
<div className="mt-4 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm leading-6 text-indigo-900"><b>Nguyên tắc:</b> hệ thống không cộng chéo tổng Cánh/Khung/Phào giữa các đơn. Mỗi bộ chỉ được tính Match khi thuộc cùng LSX và cùng cấu hình Order + Model + Size + Color + Opening + Hardware. Quality Hold hoặc thiếu thuộc tính critical sẽ chặn Matching.</div>
</main></AppShell>}
function K({t,v,tone}:{t:string;v:any;tone?:string}){const c=tone==="red"?"border-red-200 bg-red-50 text-red-700":tone==="green"?"border-emerald-200 bg-emerald-50 text-emerald-700":tone==="amber"?"border-amber-200 bg-amber-50 text-amber-700":"bg-white";return <div className={`rounded-xl border p-4 ${c}`}><div className="text-[10px] font-black uppercase">{t}</div><div className="mt-1 text-2xl font-black">{v}</div></div>}function Pill({v}:{v:string}){return <span className="rounded-full border bg-white px-2 py-1 text-[10px] font-black">{v}</span>}function Th({children}:{children:any}){return <th className="px-3 py-3 text-left">{children}</th>}function Td({children}:{children:any}){return <td className="px-3 py-3 align-top">{children}</td>}
